# -*- coding: utf-8 -*-
"""streamlit_app4_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/gymshark-rollup-5712/locations/us-central1/repositories/d85f2dfb-8f0d-4237-b819-c166b69b5143
"""

import streamlit as st

# ================== STREAMLIT PAGE CONFIG ==================
st.set_page_config(page_title="Product Quality Predictor", layout="wide")
st.title("Product Quality Predictor")
st.subheader("Check if your product is up to standard")
st.caption("Enter your qualitative feedback to see a predicted rating.")

# ================== INPUT FORM LOGIC ==================
def get_inputs():
    text = st.text_area("Below you should input your text feedback.",value="Input Here")
    return text

# ================== INPUT PARAMETERS ==================
with st.expander("⚙️ Input Parameters", expanded=True):
    text_input = get_inputs()

# ============= MODEL =============
def run_model(text):

    avg_rating_xgb = text
    is_above_4_2 = avg_rating_xgb > 4.2

    return avg_rating_xgb, is_above_4_2

# ===== SESSION STATE SETUP =====
if "avg_rating_xgb" not in st.session_state:
    st.session_state.avg_rating_xgb = None
if "is_above_4_2" not in st.session_state:
    st.session_state.is_above_4_2 = None

# ================== RUN BUTTON ==================
if st.button("🚀 Run Model"):
    with st.spinner("Running Model... please wait ⏳"):
        avg_rating_xgb, is_above_4_2 = run_model(
            text
        )

    st.success("✅ Model run complete!")

    # Save to session state
    st.session_state.avg_rating_xgb = avg_rating_xgb
    st.session_state.is_above_4_2 = is_above_4_2

# ======= If model has results, show tabs =======
if st.session_state.avg_rating_xgb is not None and st.session_state.is_above_4_2 is not None:

    tab1, tab2 = st.tabs(["Average Rating","Above 4.2?"])

    # --- Tab 1
    with tab1:
        st.metric("", f"{st.session_state.avg_rating_xgb}")

    # --- Tab 2
    with tab2:
        st.metric("", f"{st.session_state.is_above_4_2}")